import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const canvas=document.querySelector('#game');
const mphEl=document.querySelector('#mph');const bar=document.querySelector('#speedbar');const trafficEl=document.querySelector('#traffic');const statusEl=document.querySelector('#status');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8fc5ed);scene.fog=new THREE.Fog(0x8fc5ed,260,1150);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,1800);const clock=new THREE.Clock();
scene.add(new THREE.HemisphereLight(0xeaf7ff,0x385246,2.4));const sun=new THREE.DirectionalLight(0xffffff,4);sun.position.set(-250,400,180);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-600;sun.shadow.camera.right=600;sun.shadow.camera.top=600;sun.shadow.camera.bottom=-600;scene.add(sun);
const M=(c,r=.55,m=.1)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
const road=M(0x242b33,.3,.55),grass=M(0x477a52,.95,0),line=M(0xf4df8b,.7,0),window=M(0x6db7d8,.18,.5),dark=M(0x11161d,.2,.7);
const world=new THREE.Group();scene.add(world);const city=7,block=100,roadW=24;
function cube(w,h,d,ma,x,y,z,parent=world){const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),ma);q.position.set(x,y,z);q.castShadow=true;q.receiveShadow=true;parent.add(q);return q}
const ground=new THREE.Mesh(new THREE.PlaneGeometry(1600,1600),grass);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;world.add(ground);
for(let i=-city;i<=city;i++){cube(roadW,.15,1600,road,i*block,.05,0);cube(1600,.15,roadW,road,0,.055,i*block)}
for(let i=-city;i<=city;i++)for(let p=-780;p<780;p+=24){cube(.28,.08,9,line,i*block,.15,p);cube(9,.08,.28,line,p,.155,i*block)}
let seed=123456;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
for(let gx=-city;gx<city;gx++)for(let gz=-city;gz<city;gz++){const bx=gx*block+50,bz=gz*block+50;if(rnd()<.14){cube(70,.12,70,grass,bx,.12,bz);for(let n=0;n<5;n++){const x=bx-30+rnd()*60,z=bz-30+rnd()*60;cube(1,5,1,M(0x65452b),x,2.5,z);const crown=new THREE.Mesh(new THREE.SphereGeometry(4+rnd()*2,10,8),M(0x2d7546,.95));crown.position.set(x,7,z);crown.castShadow=true;world.add(crown)}}else{for(let n=0;n<2+Math.floor(rnd()*3);n++){const w=14+rnd()*20,d=14+rnd()*20,h=25+rnd()*125,x=gx*block+15+rnd()*70,z=gz*block+15+rnd()*70;cube(w,h,d,M(new THREE.Color().setHSL(.53+rnd()*.1,.2,.27+rnd()*.2),.48,.2),x,h/2,z);if(rnd()<.75)cube(w*.86,.8,d*.9,window,x,h*.48,z)}}}
for(let i=-city;i<=city;i++)for(let j=-city;j<=city;j++){for(const [x,z] of [[i*block+18,j*block+18],[i*block-18,j*block-18]]){cube(.5,8,.5,M(0x262d35,.35,.8),x,4,z);const lamp=new THREE.PointLight(0xffdca0,5,24);lamp.position.set(x,8,z);world.add(lamp)}}
function car(color){const g=new THREE.Group(),body=M(color,.24,.58);cubeLocal(4.5,1.1,8.5,body,0,1.15,0,g);cubeLocal(3.5,1.3,4.3,window,0,2.05,-.3,g);for(const x of[-2.25,2.25])for(const z of[-2.7,2.7])cubeLocal(.8,1.45,1.35,dark,x,.7,z,g);for(const x of[-1.35,1.35])cubeLocal(.7,.35,.12,M(0xffffd0,.2,.2),x,1.35,4.28,g);g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});return g}
function cubeLocal(w,h,d,ma,x,y,z,g){const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),ma);q.position.set(x,y,z);g.add(q);return q}
const player=car(new THREE.Color().setHSL(rnd(),.8,.52));scene.add(player);let pos=new THREE.Vector3(0,0,0),heading=0,speed=0;
const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR'){pos.set(0,0,0);heading=0;speed=0}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const traffic=[],colors=[0x3180ff,0xff4757,0xffc33b,0x45d59a,0xb66cff,0xffffff];
for(let i=0;i<32;i++){const horizontal=rnd()<.5,lane=(rnd()<.5?-5:5),roadLine=(Math.floor(rnd()*(city*2+1))-city)*block,c=car(colors[Math.floor(rnd()*colors.length)]);const t={c,horizontal,lane,dir:rnd()<.5?-1:1,v:20+rnd()*65};if(horizontal)c.position.set(rnd()<.5?-720:720,0,roadLine+lane);else c.position.set(roadLine+lane,0,rnd()<.5?-720:720);scene.add(c);traffic.push(t)}
function updateTraffic(dt){for(const t of traffic){const axis=t.horizontal?'x':'z';t.c.position[axis]+=t.dir*t.v*dt;t.c.rotation.y=t.horizontal?(t.dir>0?Math.PI/2:-Math.PI/2):(t.dir>0?0:Math.PI);if(t.c.position[axis]>760)t.c.position[axis]=-760;if(t.c.position[axis]<-760)t.c.position[axis]=760}}
function crash(){speed*=.3;const p=player.position.clone();for(let i=0;i<12;i++){const s=new THREE.Mesh(new THREE.SphereGeometry(.18,6,5),M(i%2?0xffc32f:0xff5630));s.position.copy(p);s.userData.v=new THREE.Vector3((rnd()-.5)*18,rnd()*12,(rnd()-.5)*18);scene.add(s);setTimeout(()=>s.removeFromParent(),600)}}
function update(dt){const f=keys.KeyW||keys.ArrowUp,b=keys.KeyS||keys.ArrowDown,boost=keys.Space,steer=(keys.KeyA||keys.ArrowLeft?-1:0)+(keys.KeyD||keys.ArrowRight?1:0);if(f)speed+=80*dt;if(boost)speed+=150*dt;if(b)speed-=130*dt;speed*=Math.pow(.985,dt*60);speed=THREE.MathUtils.clamp(speed,-45,500);heading-=steer*dt*(.8+Math.min(Math.abs(speed)/80,3));pos.x+=Math.sin(heading)*speed*dt*.22;pos.z+=Math.cos(heading)*speed*dt*.22;pos.x=THREE.MathUtils.clamp(pos.x,-770,770);pos.z=THREE.MathUtils.clamp(pos.z,-770,770);player.position.set(pos.x,0,pos.z);player.rotation.y=heading;for(const t of traffic){if(player.position.distanceTo(t.c.position)<5){crash();t.c.position.x+=Math.sign(t.c.position.x-pos.x)*8;t.c.position.z+=Math.sign(t.c.position.z-pos.z)*8}}}
function cameraFollow(dt){const target=new THREE.Vector3(-Math.sin(heading)*17,8,-Math.cos(heading)*17).add(player.position);camera.position.lerp(target,1-Math.pow(.001,dt));camera.lookAt(player.position.x,2,player.position.z)}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.033);update(dt);updateTraffic(dt);cameraFollow(dt);const v=Math.round(Math.abs(speed));mphEl.innerHTML=v+' <small>MPH</small>';bar.style.width=Math.min(v/500*100,100)+'%';trafficEl.textContent='TRAFFIC: '+traffic.length;statusEl.textContent='DRIVE CITY · LIVE';renderer.render(scene,camera)}
loop();