import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=s=>document.querySelector(s),canvas=$('#game'),mphEl=$('#mph'),bar=$('#speedbar'),trafficEl=$('#traffic'),statusEl=$('#status');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8fc8ee);scene.fog=new THREE.Fog(0x8fc8ee,300,1200);const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,1800);const clock=new THREE.Clock();
scene.add(new THREE.HemisphereLight(0xeaf7ff,0x46634d,2.7));const sun=new THREE.DirectionalLight(0xffffff,4.2);sun.position.set(-220,360,180);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const M=(c,r=.55,m=.1)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m}),road=M(0x222a33,.3,.55),grass=M(0x4b8056,.95),line=M(0xf6e59a,.75),glass=M(0x70b9da,.15,.55),dark=M(0x10151b,.2,.75);const world=new THREE.Group();scene.add(world);const city=7,block=100,roadW=24;
function box(w,h,d,m,x,y,z,p=world){const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);q.position.set(x,y,z);q.castShadow=true;q.receiveShadow=true;p.add(q);return q}const ground=new THREE.Mesh(new THREE.PlaneGeometry(1700,1700),grass);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;world.add(ground);
for(let i=-city;i<=city;i++){box(roadW,.16,1700,road,i*block,.03,0);box(1700,.16,roadW,road,0,.04,i*block)}for(let i=-city;i<=city;i++)for(let p=-830;p<830;p+=24){box(.22,.08,9,line,i*block,.14,p);box(9,.08,.22,line,p,.14,i*block)}
let seed=918273;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
for(let gx=-city;gx<city;gx++)for(let gz=-city;gz<city;gz++){if(rnd()<.15){box(72,.1,72,grass,gx*block+50,.09,gz*block+50);for(let n=0;n<5;n++){let x=gx*block+18+rnd()*64,z=gz*block+18+rnd()*64;box(1.2,5,1.2,M(0x62432a),x,2.5,z);let c=new THREE.Mesh(new THREE.SphereGeometry(4+rnd()*2,10,8),M(0x2e7247,.9));c.position.set(x,7,z);c.castShadow=true;world.add(c)}}else for(let n=0;n<2+Math.floor(rnd()*3);n++){let w=14+rnd()*20,d=14+rnd()*20,h=22+rnd()*125,x=gx*block+14+rnd()*72,z=gz*block+14+rnd()*72;box(w,h,d,M(new THREE.Color().setHSL(.53+rnd()*.1,.22,.29+rnd()*.18),.45,.18),x,h/2,z);if(rnd()<.7)box(w*.86,.8,d*.9,glass,x,h*.55,z)}}
function local(w,h,d,m,x,y,z,g){let q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);q.position.set(x,y,z);g.add(q);return q}function car(color){let g=new THREE.Group(),body=M(color,.23,.62);local(4.5,1.05,8.4,body,0,1.25,0,g);local(3.4,1.3,4.4,glass,0,2.15,-.2,g);for(let x of[-2.15,2.15])for(let z of[-2.7,2.7])local(.75,1.15,1.4,dark,x,.7,z,g);for(let x of[-1.35,1.35])local(.65,.35,.12,M(0xffffd0,.15,.2),x,1.38,4.18,g);g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});return g}
const player=car(new THREE.Color().setHSL(rnd(),.82,.55));scene.add(player);let pos=new THREE.Vector3(),heading=0,speed=0;const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR'){pos.set(0,0,0);heading=0;speed=0}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const traffic=[],tc=[0x3182ff,0xff4757,0xffc33b,0x45d59a,0xb66cff,0xffffff];for(let i=0;i<28;i++){let h=rnd()<.5,l=(rnd()<.5?-5:5),r=(Math.floor(rnd()*(city*2+1))-city)*block,c=car(tc[Math.floor(rnd()*tc.length)]);let t={c,h,l,v:22+rnd()*58,d:rnd()<.5?-1:1};if(h)c.position.set(rnd()<.5?-700:700,0,r+l);else c.position.set(r+l,0,rnd()<.5?-700:700);scene.add(c);traffic.push(t)}
function trafficUpdate(dt){for(let t of traffic){let a=t.h?'x':'z';t.c.position[a]+=t.d*t.v*dt;t.c.position.y=0;t.c.rotation.y=t.h?(t.d>0?Math.PI/2:-Math.PI/2):(t.d>0?0:Math.PI);if(t.c.position[a]>740)t.c.position[a]=-740;if(t.c.position[a]<-740)t.c.position[a]=740}}
function update(dt){let f=keys.KeyW||keys.ArrowUp,b=keys.KeyS||keys.ArrowDown,a=(keys.KeyA||keys.ArrowLeft?-1:0)+(keys.KeyD||keys.ArrowRight?1:0);if(f)speed+=80*dt;if(keys.Space)speed+=150*dt;if(b)speed-=130*dt;speed*=Math.pow(.985,dt*60);speed=THREE.MathUtils.clamp(speed,-45,500);heading-=a*dt*(.8+Math.min(Math.abs(speed)/80,3));pos.x+=Math.sin(heading)*speed*dt*.22;pos.z+=Math.cos(heading)*speed*dt*.22;pos.x=THREE.MathUtils.clamp(pos.x,-770,770);pos.z=THREE.MathUtils.clamp(pos.z,-770,770);player.position.set(pos.x,0,pos.z);player.rotation.y=heading;for(let t of traffic)if(player.position.distanceTo(t.c.position)<5){speed*=.25;t.v*=.7}}
function cameraUpdate(dt){let target=new THREE.Vector3(-Math.sin(heading)*17,8,-Math.cos(heading)*17).add(player.position);camera.position.lerp(target,1-Math.pow(.001,dt));camera.lookAt(pos.x,2,pos.z)}
function animate(){requestAnimationFrame(animate);let dt=Math.min(clock.getDelta(),.033);update(dt);trafficUpdate(dt);cameraUpdate(dt);let v=Math.round(Math.abs(speed));mphEl.innerHTML=v+' <small>MPH</small>';bar.style.width=Math.min(v/500*100,100)+'%';trafficEl.textContent='TRAFFIC: '+traffic.length;statusEl.textContent='DRIVE CITY · LIVE';renderer.render(scene,camera)}
animate();
